import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Prefectures from "@/components/Prefectures";
import Graph from "@/components/Graph";
import { useState, useEffect } from "react";
import { useFetchPrefectureName } from "@/hooks/useFetchPrefectureName";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [prefectures, setPrefectures] = useState(null);
  const [prefPopulation, setPrefPopulation] = useState([]);

  useFetchPrefectureName().then((prefectureList) => {
    if (prefectures == null) {
      setPrefectures(prefectureList);
    }
  });

  const fetchPopulation = async (prefCode) => {
    try {
      const fetchedPopulationData = await fetch("https://opendata.resas-portal.go.jp/api/v1/population/composition/perYear?prefCode=" + prefCode, {
        method: "GET",
        headers: {
          "X-API-KEY": process.env.NEXT_PUBLIC_APIKEY,
        },
      });

      const jsonPopulation = await fetchedPopulationData.json();
      const populationList = jsonPopulation.result;
      return populationList;
    } catch (error) {
      window.alert("データ取得に失敗しました");
    }
  };

  const handleCheck = (prefName, prefCode, check) => {
    let availPrefPopulation = [...prefPopulation];

    if (check) {
      if (availPrefPopulation.findIndex((value) => value.prefName === prefName) !== -1) return;
      fetchPopulation(prefCode)
        .then((results) => {
          availPrefPopulation.push({
            prefName: prefName,
            data: results.data,
            // data: results.data[0].data,
          });

          setPrefPopulation(availPrefPopulation);
        })
        .catch((error) => {
          return;
        });
    } else {
      const deleteIndex = availPrefPopulation.findIndex((value) => value.prefName === prefName);
      if (deleteIndex === -1) return;
      availPrefPopulation.splice(deleteIndex, 1);
      setPrefPopulation(availPrefPopulation);
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Prefectures prefectures={prefectures} onChange={handleCheck} />
        <Graph populationList={prefPopulation} />
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
              By <Image src="/vercel.svg" alt="Vercel Logo" className={styles.vercelLogo} width={100} height={24} priority />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image className={styles.logo} src="/next.svg" alt="Next.js Logo" width={180} height={37} priority />
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>Find in-depth information about Next.js features and&nbsp;API.</p>
          </a>

          <a href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>Discover and deploy boilerplate example Next.js&nbsp;projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card} target="_blank" rel="noopener noreferrer">
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.</p>
          </a>
        </div> */}
      </main>
    </>
  );
}
